### ISSUE TITLE
Typo in main.js prevent correct use

### ISSUE THREAD

**Issue by niklasbirk** [Nununuru/Subatimer-Subathon-Timer-for-Streamelements#1]
`addSecondsThroughEvent(checkAndConsiderHappyHour(amount * fields.tipsIncrease, ['tip', 'dono', 'dontation']) , name);` in line 157:[main.js](https://github.com/Nununuru/Subatimer-Subathon-Timer-for-Streamelements/blob/main/main.js)

`dontation` instead of `donation`

**Comment by Nununuru** [comment]
Thanks Sir Nik :3 Good catch
